FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

COPY Common/Common.csproj .
COPY Core/Core.csproj .
COPY Presentation/Presentation.csproj .

RUN dotnet restore Common.csproj
RUN dotnet restore Core.csproj
RUN dotnet restore Presentation.csproj

COPY . .
RUN dotnet build Common/Common.csproj -c Release -o /app/build
RUN dotnet build Core/Core.csproj -c Release -o /app/build
RUN dotnet build Presentation/Presentation.csproj -c Release -o /app/build

FROM build AS publish
RUN dotnet publish Common/Common.csproj -c Release -o /app/publish
RUN dotnet publish Core/Core.csproj -c Release -o /app/publish
RUN dotnet publish Presentation/Presentation.csproj -c Release -o /app/publish

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwwroot .
COPY Presentation/nginx.conf /etc/nginx/nginx.conf