name: Build docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v2
    
    - name: Docker Version
      uses: docker --version

    - name: Build Docker Image
      run: docker build --no-cache

    - name: Run Docker Image
      run: docker compose up -d

    - name: Run Docker Image
      run: |
        docker kill $(docker ps -q)
        docker rm $(docker ps -a -q)