name: Build Dotnet Solution

on:  
  pull_request:
    branches:
    - main
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x' 

      - name: Restore Common NuGet packages
        run: dotnet restore src/Common/Common.csproj 

      - name: Build Common
        run: dotnet build src/Common/Common.csproj 

      - name: Restore Core NuGet packages
        run: dotnet restore src/Core/Core.csproj 

      - name: Build Core
        run: dotnet build src/Core/Core.csproj 

      - name: Restore Presentation NuGet packages
        run: dotnet restore src/Presentation/Presentation.csproj 

      - name: Build Presentation
        run: dotnet build src/Presentation/Presentation.csproj 

      - name: Build Presentation Tests
        run: dotnet build src/PresentationTests/PresentationTests.csproj 

      - name: Run Presentation Tests
        run: dotnet test src/PresentationTests/PresentationTests.csproj 

