name: Build and Test

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x' 

      - name: Restore NuGet packages
        run: dotnet restore DashboardX.csproj DashboardXModels.csproj

      - name: Build the project
        run: dotnet build --configuration Release DashboardX.csproj DashboardXModels.csproj

      - name: Run tests (if you have tests)
        run: dotnet test --configuration Release --no-restore --verbosity normal

