name: Build and Test

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x' 

      - name: Restore Common NuGet packages
        run: dotnet restore DashboardX/Common/Common.csproj 

      - name: Build Common
        run: dotnet build DashboardX/Common/Common.csproj 

      - name: Restore Core NuGet packages
        run: dotnet restore DashboardX/Core/Core.csproj 

      - name: Build Core
        run: dotnet build DashboardX/Core/Core.csproj 

      - name: Restore Presentation NuGet packages
        run: dotnet restore DashboardX/Presentation/Presentation.csproj 

      - name: Build Presentation
        run: dotnet build DashboardX/Presentation/Presentation.csproj 

